version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: alaffia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_shadow:
    image: postgres:13
    environment:
      POSTGRES_DB: alaffia_db_shadow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_shadow:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - db_shadow
    ports:
      - "5000:5000"
    command: npx nodemon --exec ts-node src/index.ts
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules

volumes:
  postgres_data:
  postgres_data_shadow:
