version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: alaffia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db/alaffia_db
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
